// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA08VI-7UNLhq2fuMhPW7ZDnTQSMRanhfQ',
    appId: '1:953863667017:web:2072d677ca7fa6d7232e98',
    messagingSenderId: '953863667017',
    projectId: 'to-do-app-b455a',
    authDomain: 'to-do-app-b455a.firebaseapp.com',
    storageBucket: 'to-do-app-b455a.appspot.com',
    measurementId: 'G-79K9SNC0X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkRdYv6mNWOEqYKlmzQpcMN3XpPaVLKSE',
    appId: '1:953863667017:android:1ba23c9ad1e087b3232e98',
    messagingSenderId: '953863667017',
    projectId: 'to-do-app-b455a',
    storageBucket: 'to-do-app-b455a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw9GZaIQCsylBldcTz7EgRAhY5A7HoLMQ',
    appId: '1:953863667017:ios:08eeeec9a3b220fa232e98',
    messagingSenderId: '953863667017',
    projectId: 'to-do-app-b455a',
    storageBucket: 'to-do-app-b455a.appspot.com',
    androidClientId: '953863667017-jtbalm95qco005kl3cqegld1e5o2lfln.apps.googleusercontent.com',
    iosClientId: '953863667017-6513p3uer2719drhrd0lijp2l7ur7gsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw9GZaIQCsylBldcTz7EgRAhY5A7HoLMQ',
    appId: '1:953863667017:ios:08eeeec9a3b220fa232e98',
    messagingSenderId: '953863667017',
    projectId: 'to-do-app-b455a',
    storageBucket: 'to-do-app-b455a.appspot.com',
    androidClientId: '953863667017-jtbalm95qco005kl3cqegld1e5o2lfln.apps.googleusercontent.com',
    iosClientId: '953863667017-6513p3uer2719drhrd0lijp2l7ur7gsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA08VI-7UNLhq2fuMhPW7ZDnTQSMRanhfQ',
    appId: '1:953863667017:web:ffbe81d72bf18a7f232e98',
    messagingSenderId: '953863667017',
    projectId: 'to-do-app-b455a',
    authDomain: 'to-do-app-b455a.firebaseapp.com',
    storageBucket: 'to-do-app-b455a.appspot.com',
    measurementId: 'G-P63Q57K9D0',
  );

}